In [1]:
import numpy as np

In [5]:
# create rank 1 dim array
arr = np.array([1,2,3])
print(type(arr))            # outputs <class 'numpy.ndarray'>
print(arr.dtype)            # outputs data type
print(arr.shape)            # outputs array shape
print(arr[0], arr[1], arr[2])  # prints individual elements
arr[2] = 4                  # changes element
print(arr)

# create rank 2 array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2.shape)
print(arr2[0,0], arr2[0,1], arr2[1,0])
print(arr2[-1])             #prints last element


<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]


In [6]:
# create an array of zeros with 2 dim and size of 2 each
zero = np.zeros((2,2))
print(zero)

# create an array of ones with 1 dim and size of 2 each
one = np.ones((1,2))
print(one)

# create a new array with given shape, type, and filled with value
constant = np.full((2,2), 5)
print(constant)

# create a 2-D array with 1 on diagonal and 0 on others
diag = np.eye(3)
print(diag)

#diag starts at index 1
diag = np.eye(4, k=1)
print(diag)

#create an array with random values
rand = np.random.random((2,2))
print(rand)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.47415861 0.23636407]
 [0.7309936  0.99476703]]


In [7]:
arr = np.arange(10)
print(arr[0:8:2])           # print every two numbers from 0 up to but not including 8

#create rank2 with shape (3,4) array
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[:2, :2])          # prints the first to elements in the first two indexes [1,2] & [5,6]



[0 2 4 6]
[[1 2]
 [5 6]]


In [8]:
#integer indexing
arr = np.array([[1,2], [3,4], [5,6]])
print(arr[[0,1,2], [0,1,1]])        # equivalent to [arr[0,0], arr[1,1,arr[2,1]]]


[1 4 6]


In [9]:
# reshape: gives a new shape to an array without chaging its data
arr = np.arange(9)
print(arr)
reshape_arr = arr.reshape(3,3)
print(reshape_arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# flat: iterator over the array turned into 1-D array
arr = np.arange(8).reshape(2,4)
print(arr)
print(arr.flat[4])

[[0 1 2 3]
 [4 5 6 7]]
4


In [11]:
#flatten: collapse to 1-D array and return a copy of the  array
arr = np.arange(8).reshape(2,4)
print(arr)
print(arr.flatten())

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


In [12]:
#transpose: permutes the dimentions of an array
arr = np.arange(8).reshape(2,4)
print(arr)
print(arr.transpose())

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [14]:
#broadcast: Produces an object tha mimics broadcasting.
# numpy built-in support broadcasting
a = np.array([[1], [2], [3]])
b = np.array([4,5,6])
c = a + b                       # [[1+4, 2+4, 3+4], [1+5, and so on], [1+6, and so on]]
print(c)

bc = np.broadcast(a,b)
x = np.zeros(bc.shape)
print(bc)
print(x)

x.flat = [a+b for (a,b) in bc]      # turn x into 1-D array for get all values after adding them
print(x)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [15]:
#resize: returns a new array with the specified shape
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
arr_resized = np.resize(arr, (3,3))
print(arr_resized)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [18]:
#unique: finds the unique elements of an array
unique = np.unique([1,1,2,2,3,3])
print(unique)

arr = np.array([[1,1], [2,3]])
print(np.unique(arr))

arr = np.array(['a', 'b', 'b', 'c', 'a'])
unique, indices = np.unique(arr, return_index=True)     #returns index of the first unque values
print(unique, indices)

count = np.unique(arr, return_counts=True)
print(count[0], count[1])                               #first array is unique value, second is number of occurances


[1 2 3]
[1 2 3]
['a' 'b' 'c'] [0 1 3]
['a' 'b' 'c'] [2 2 1]
