In [ ]:
#filtering out missing data

In [11]:
from numpy import nan as NA
import pandas as pd
import numpy as np
np.random.seed(12345)


In [2]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna(how='all')
cleaned

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [9]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [10]:
data.dropna(axis = 1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [14]:
df.dropna(thresh=2)

0         1         2
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [18]:
# filling in missing data
df.fillna(3)

0         1         2
0 -0.204708  3.000000  3.000000
1 -0.555730  3.000000  3.000000
2  0.092908  3.000000  0.769023
3  1.246435  3.000000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [19]:
df.fillna({1:0.5, 2:0})

0         1         2
0 -0.204708  0.500000  0.000000
1 -0.555730  0.500000  0.000000
2  0.092908  0.500000  0.769023
3  1.246435  0.500000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [20]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA
df

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772       NaN  1.343810
3 -0.713544       NaN -2.370232
4 -1.860761       NaN       NaN
5 -1.265934       NaN       NaN

In [21]:
df.fillna(method='ffill')

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761  0.124121 -2.370232
5 -1.265934  0.124121 -2.370232

In [24]:
df.fillna(method='ffill', limit=3)

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761  0.124121 -2.370232
5 -1.265934       NaN -2.370232

In [25]:
data = pd.Series([1.,NA,3.5,NA,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [26]:
#7.2 data transformation- removing duplicates
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [27]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [28]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [29]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [30]:
data.drop_duplicates(['k1','k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [31]:
#data transformation - transforming data using a function or mapping
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [36]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}


In [37]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [38]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [39]:
data['food'].map(lambda x : meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [40]:
#data transformation - replacing values
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [43]:
data.replace([-999,-1000], [np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [44]:
#data transformation - remaning axis indexes
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [45]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [49]:
transform = lambda x : x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [50]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [51]:
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [52]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [53]:
data.rename(index={'OHIO':'INDIANA'}, columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [58]:
#data transformation- discretization and binning
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18,25,35,60,100]
cats = pd.cut(ages, bins)
cats


[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [60]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [61]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [62]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [63]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [65]:
data = np.random.rand(20)
data

array([0.24497444, 0.7928007 , 0.49517241, 0.91509367, 0.94537183,
       0.53323223, 0.25249259, 0.72086206, 0.36743876, 0.49864844,
       0.22657505, 0.35356565, 0.65085179, 0.3129329 , 0.76873545,
       0.7818371 , 0.85240948, 0.94990574, 0.10732291, 0.91072536])

In [66]:
pd.cut(data, 4, precision=2)

[(0.11, 0.32], (0.74, 0.95], (0.32, 0.53], (0.74, 0.95], (0.74, 0.95], ..., (0.74, 0.95], (0.74, 0.95], (0.74, 0.95], (0.11, 0.32], (0.74, 0.95]]
Length: 20
Categories (4, interval[float64]): [(0.11, 0.32] < (0.32, 0.53] < (0.53, 0.74] < (0.74, 0.95]]

In [70]:
data = np.random.randn(1000)
cats = pd.qcut(data,4)
cats

[(-0.0309, 0.613], (0.613, 3.928], (-0.686, -0.0309], (-0.686, -0.0309], (-2.9499999999999997, -0.686], ..., (-2.9499999999999997, -0.686], (-2.9499999999999997, -0.686], (-0.686, -0.0309], (0.613, 3.928], (-2.9499999999999997, -0.686]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.686] < (-0.686, -0.0309] < (-0.0309, 0.613] < (0.613, 3.928]]

In [74]:
pd.value_counts(cats)

(0.613, 3.928]                   250
(-0.0309, 0.613]                 250
(-0.686, -0.0309]                250
(-2.9499999999999997, -0.686]    250
dtype: int64

In [75]:
a =pd.qcut(data,[0,0.1,0.5,0.9,1.])
a


[(-0.0309, 1.287], (-0.0309, 1.287], (-1.187, -0.0309], (-1.187, -0.0309], (-1.187, -0.0309], ..., (-1.187, -0.0309], (-1.187, -0.0309], (-1.187, -0.0309], (1.287, 3.928], (-2.9499999999999997, -1.187]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -1.187] < (-1.187, -0.0309] < (-0.0309, 1.287] < (1.287, 3.928]]

In [76]:
pd.value_counts(a)

(-0.0309, 1.287]                 400
(-1.187, -0.0309]                400
(1.287, 3.928]                   100
(-2.9499999999999997, -1.187]    100
dtype: int64

In [78]:
#data transformation -detecting and filtering outliers
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.003027    -0.002242    -0.057075    -0.050750
std       1.040705     1.017119     0.979049     1.001540
min      -3.183867    -3.481593    -3.194414    -3.108915
25%      -0.740508    -0.696704    -0.753809    -0.736424
50%       0.016668     0.034523    -0.054956    -0.038821
75%       0.700698     0.702548     0.616784     0.601663
max       3.189940     2.961194     3.023720     2.916153

In [80]:
data

0         1         2         3
0   -1.394656 -0.281825  0.109331 -0.444135
1    1.442611  0.342310  0.299675 -0.550621
2    1.809901  0.025721 -0.161442  2.771398
3    0.460863  1.694641 -0.935589  0.766984
4   -2.040757 -0.882594 -1.131414  0.490516
..        ...       ...       ...       ...
995 -0.887796  0.372837 -0.850192 -0.686489
996  0.207363 -0.266300  0.253912 -1.270547
997  0.682816 -0.648243  0.433294  0.157510
998  1.386222  0.010130  0.457039 -0.338315
999  0.591852  0.502152 -0.798525 -0.176708

[1000 rows x 4 columns]

In [82]:
col = data[2]

In [83]:
col[np.abs(col) >3]

470   -3.194414
500    3.023720
890   -3.044612
Name: 2, dtype: float64

In [85]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
21   0.336788 -3.333767 -1.240685 -0.650855
103 -3.018842 -0.298748  0.406954  0.183282
127  0.781753 -0.555434 -0.048478 -3.108915
258 -3.183867  1.050471 -1.042736  1.680374
305 -3.140963 -1.509976 -0.389818 -0.273253
470  1.090038 -0.848098 -3.194414  0.077839
500  0.003349 -0.011807  3.023720 -1.105312
529  0.452649 -3.481593  0.789944  1.737746
698  3.082067 -0.516982  0.251909 -0.029354
726  3.189940  0.070978  0.516982 -0.805171
890 -0.436479  0.901529 -3.044612 -1.193980
924 -1.148738 -3.170292 -1.017073 -1.147658

In [90]:
data[np.abs(data)>3] = np.sign(data) * 3
data.describe()


0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.002955    -0.001256    -0.056860    -0.050641
std       1.038880     1.014022     0.978234     1.001213
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.740508    -0.696704    -0.753809    -0.736424
50%       0.016668     0.034523    -0.054956    -0.038821
75%       0.700698     0.702548     0.616784     0.601663
max       3.000000     2.961194     3.000000     2.916153

In [93]:
#data transformation - permutation and random sampling
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler = np.random.permutation(5)
sampler

array([4, 2, 0, 3, 1])

In [94]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7

In [95]:
df.sample(2)

0   1   2   3
1   4   5   6   7
4  16  17  18  19

In [96]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

3    6
1    7
4    4
1    7
3    6
2   -1
0    5
2   -1
3    6
0    5
dtype: int64

In [97]:
#data transformation - computing indicator /dummy variables
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [100]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [101]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [102]:
np.random.seed(12345)

In [104]:
values = np.random.rand(10)
values

array([0.74771481, 0.96130674, 0.0083883 , 0.10644438, 0.29870371,
       0.65641118, 0.80981255, 0.87217591, 0.9646476 , 0.72368535])

In [106]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           1           0
1           0           0           0           0           1
2           1           0           0           0           0
3           1           0           0           0           0
4           0           1           0           0           0
5           0           0           0           1           0
6           0           0           0           0           1
7           0           0           0           0           1
8           0           0           0           0           1
9           0           0           0           1           0