In [64]:
import numpy as np
nsteps = 1000
draws = np.random.randint(0,2,size=nsteps)
steps = np.where(draws>0,1,-1)
walk = steps.cumsum()

2


In [27]:
np.random.seed(1234)
samples = np.random.normal(-2,5,size=(3,4))
print(samples)

[[  0.35717582  -7.95487847   5.16353484  -3.56325948]
 [ -5.60294367   2.4358147    2.29794207  -5.18261752]
 [ -1.92151814 -13.21342477   3.75017862   2.95973011]]


In [69]:
import numpy as np
nwalks=5000
nsteps=1000
np.random.seed(1234)
draws = np.random.normal(loc=0,scale=0.25,size=(nwalks,nsteps))
steps = np.where(draws > 0,1,-1)
walks = steps.cumsum(1)
hitN50 = (walks==-50).any(1)
print(hitN50.sum())
crossing_time = (walks[hitN50]==-50).argmax(1)
print(crossing_time.mean())

print(walks[hitN50])
print("====")
print(walks[hitN50]==-50)
print("====")
print(walks)

604
679.7218543046357
[[ -1  -2  -3 ... -46 -45 -46]
 [  1   0  -1 ... -36 -37 -38]
 [  1   0  -1 ... -20 -19 -20]
 ...
 [ -1  -2  -3 ... -38 -39 -40]
 [ -1  -2  -3 ... -44 -45 -44]
 [  1   2   1 ...  -8  -9  -8]]
====
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
====
[[  1   0   1 ...  14  15  14]
 [ -1  -2  -1 ...  24  25  24]
 [ -1   0  -1 ...  24  25  26]
 ...
 [  1   2   1 ...  -8  -9  -8]
 [  1   0   1 ... -20 -21 -20]
 [  1   2   3 ... -14 -13 -14]]
