In [ ]:
import numpy as np 

In [2]:
import numpy as np 

#create rank 1 dim array
arr = np.array([1, 2, 3])                   
print(type(arr))                            #outputs <class 'numpy.ndarrray>          
print(arr.dtype)                            #outputs int64              
print(arr.shape)                            #outputs (3,)
print(arr[0], arr[1], arr[2])               #outputs 1 2 3
arr[2] = 4                                  #change last element to 4
print(arr)                                  #output 1 2 4

#crete rank 2 array
arr2 = np.array([[1,2,3], [4,5,6]])         
print(arr2.shape)                           #output (2, 3)
print(arr2[0,0], arr2[0,1], arr2[1,0])      #output 1 2 4
print(arr2[-1])                             #outputs last element 4 5 6


<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]


In [3]:
import numpy as np 
#create an array of zeros with 2 dimension and size of 2
zero = np.zeros((2,2))
print (zero)           #outputs "[[0. 0.]
                       #         [0. 0.]"

#create an array of ones with 1 dim and size of 2 each
one = np.ones((1,2))
print (one)             #outputs "[[1. 1.]]"

#create a new array with given shape, type and filled with value
constant = np.full((2,2), 5)    #default type is float
print(constant)                 #diytoyts "[[5 5
                                #           [5 5]]"
                                
#create a 2-D array with 1 on diagonal and 0 others
diag = np.eye(3)                #number of rows
                                #outputs [[1. 0. 0.]]
                                #        [0. 1. 0]
                                #        [0. 0. 1.]]

#diag starts at index 1
diag = np.eye(4, k=1)
print(diag)                 #outputs [[0. 1. 0. 0.]]
                            #         [0. 0. 1. 0.]
                            #         [0. 0. 0. 1.]
                            #         [0. 0. 0. 0.]]

#create an array with random values
rand = np.random.random((2,2))
print(rand)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.17945559 0.89607018]
 [0.00171455 0.23195973]]


In [4]:
#Array indexing

arr = np.arange(10)         #generate array [0 1 2 3 4 5 6 7 8 9]
print (arr[0:8:2])          #every two number from 0 up to but not include 8

#create rank 2 with shape (3, 4) array
arr = np.array([[1,2,3,4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:2, :2])          #outputs [[1 2]]
                            #        [5 6]

[0 2 4 6]
[[1 2]
 [5 6]]


In [5]:
#integer indexing

arr = np.array([[1,2], [3,4], [5,6]])
print(arr[[0, 1, 2], [0, 1, 1]])        #outputs [1 4 6]



[1 4 6]


In [ ]:
reshape()   

In [6]:
arr = np.arange(9)              #create [0, 1, 2, 3, 4, 5, 6, 7, 8]
reshape_arr = arr.reshape(3, 3) #reshape 1-D arr to 2-D with (3,3)
print(reshape_arr)              #outputs [[0 1 2]
                                #         [3 4 5]
                                #         [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
flat[]

In [9]:
arr = np.arange(8).reshape(2, 4)
print(arr.flat[4])

4


In [ ]:
flatten()
#collapse to 1-d and return a copy of the array

In [10]:
arr = np.arange(8).reshape(2, 4)
print(arr.flatten())

[0 1 2 3 4 5 6 7]


In [ ]:
transpose()
#permutes the dimensions of an array

In [11]:
arr = np.arange(8).reshape(2, 4)
print(arr.transpose())

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [ ]:
broadcast()
#Produce an object that mimics broadcasting. Broadcasting is a powerful mechanis that allows numpy to work with arrays of different shapes when performing arithmetic operations

In [14]:
#numpy built-in supports broadcasting
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
c = a + b
print(c)

#this is what it was doing for us
bc = np.broadcast(a, b)     
x = np.zeros(bc.shape)

x.flat = [a + b for (a,b) in bc]
print(x)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [ ]:
resize()
#dReturns a new array with the specified shape. If the new size is greater than the orginal, the repeated copies of entries in the original are contained

In [15]:
arr = np.array([[1,2,3], [4,5,6]])
arr_resized = np.resize(arr, (3,3))
print(arr_resized)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [ ]:
unique()
#Finds the unique elements of an array

In [16]:
unique = np.unique([1, 1, 2, 2, 3, 3])
print(unique)               #output [1 2 3]

arr = np.array([[1, 1], [2, 3]])
print(np.unique(arr))       #output [1 2 3]

arr = np.array(['a', 'b', 'b', 'c', 'a'])
unique, indices = np.unique(arr, return_index=True)
print(unique, indices)

count = np.unique(arr, return_counts=True)
print(count[0], count[1])

[1 2 3]
[1 2 3]
['a' 'b' 'c'] [0 1 3]
['a' 'b' 'c'] [2 2 1]
