In [1]:
import numpy as np



In [10]:
arr = np.array([1,2,3])
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr[0], arr[1], arr[2])
arr[2] = 4
print(arr)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)
print(arr2[0,0], arr2[0,1], arr2[1,0])
print(arr2[-1])

zero = np.zeros((2,2))
print(zero)

one = np.ones((1,2))
print(one)

diag = np.eye(3)
print(diag)

rand = np.random.random((2,2))
print(rand)

arr = np.arange(10)
print(arr[0:8:2])

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:2, :2])



<class 'numpy.ndarray'>
int64
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]
[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.33645237 0.09035908]
 [0.92399869 0.61702193]]
[0 2 4 6]
[[1 2]
 [5 6]]


In [11]:
arr = np.arange(9)
reshape_arr = arr.reshape(3,3)
print(reshape_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
