In [1]:
import numpy as np
import pandas as pd

In [2]:
trans = pd.DataFrame({"A":[12, 4, 5, None, 1],
                      "B":[7, 2, 54, 3, None], 
                      "C":[20, 16, 11, 3, 8], 
                      "D":[14, 3, None, 2, 6]},
                      index=['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5'])
trans

A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

In [3]:
result = trans.transform(lambda x : x + 10)
result

A     B   C     D
Row_1  22.0  17.0  30  24.0
Row_2  14.0  12.0  26  13.0
Row_3  15.0  64.0  21   NaN
Row_4   NaN  13.0  13  12.0
Row_5  11.0   NaN  18  16.0

In [5]:
result2 = trans.transform([np.sqrt, np.exp])
result2

A                        B                       C  \
           sqrt            exp      sqrt           exp      sqrt   
Row_1  3.464102  162754.791419  2.645751  1.096633e+03  4.472136   
Row_2  2.000000      54.598150  1.414214  7.389056e+00  4.000000   
Row_3  2.236068     148.413159  7.348469  2.830753e+23  3.316625   
Row_4       NaN            NaN  1.732051  2.008554e+01  1.732051   
Row_5  1.000000       2.718282       NaN           NaN  2.828427   

                            D                
                exp      sqrt           exp  
Row_1  4.851652e+08  3.741657  1.202604e+06  
Row_2  8.886111e+06  1.732051  2.008554e+01  
Row_3  5.987414e+04       NaN           NaN  
Row_4  2.008554e+01  1.414214  7.389056e+00  
Row_5  2.980958e+03  2.449490  4.034288e+02

In [6]:
x = np.random.randint(10, 200, size=10)
x

array([195, 160, 111, 132, 107,  89, 158,  97,  80, 103])

In [8]:
np.digitize(x,bins=[50])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
np.digitize(x,bins=[50, 100])

array([2, 2, 2, 2, 2, 1, 2, 1, 1, 2])

In [11]:
df =pd.DataFrame({"height": x})
df

height
0     195
1     160
2     111
3     132
4     107
5      89
6     158
7      97
8      80
9     103

In [12]:
df['binned'] = pd.cut(x=df['height'], bins=[0, 25, 50, 100, 200])
df

height      binned
0     195  (100, 200]
1     160  (100, 200]
2     111  (100, 200]
3     132  (100, 200]
4     107  (100, 200]
5      89   (50, 100]
6     158  (100, 200]
7      97   (50, 100]
8      80   (50, 100]
9     103  (100, 200]

In [13]:
df['bin_label'] = pd.cut(x = df['height'],
                            bins = [0, 25, 50, 100, 200],
                            labels = [1, 2, 3, 4])
df

height      binned bin_label
0     195  (100, 200]         4
1     160  (100, 200]         4
2     111  (100, 200]         4
3     132  (100, 200]         4
4     107  (100, 200]         4
5      89   (50, 100]         3
6     158  (100, 200]         4
7      97   (50, 100]         3
8      80   (50, 100]         3
9     103  (100, 200]         4

In [14]:
pd.qcut(df['height'], q=5)

0    (158.4, 195.0]
1    (158.4, 195.0]
2    (105.4, 119.4]
3    (119.4, 158.4]
4    (105.4, 119.4]
5    (79.999, 95.4]
6    (119.4, 158.4]
7     (95.4, 105.4]
8    (79.999, 95.4]
9     (95.4, 105.4]
Name: height, dtype: category
Categories (5, interval[float64]): [(79.999, 95.4] < (95.4, 105.4] < (105.4, 119.4] < (119.4, 158.4] < (158.4, 195.0]]