In [1]:
import numpy as np

In [4]:
#create rank 1 dim array
arr = np.array([1,2,3])
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr[0], arr[1], arr[2])
arr[2]=4
print(arr)

#create rank 2 array
arr2 = np.array([(1,2,3),(4,5,6)])
print(arr2.shape)
print(arr2[0,0], arr2[0,1], arr2[1,0])
print(arr2[-1])


<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]


In [5]:
zero =  np.zeros((2,2))
print(zero)

one= np.ones((1,2))
print(one)

constant= np.full((2,2), 5)
print(constant)

diag =np.eye(3)
print(diag)

diag =np.eye(4, k=1)
print(diag)

rand= np.random.random((2,2))
print(rand)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.00816973 0.56350317]
 [0.73847561 0.96917937]]


In [7]:
#Array indexing
arr = np.arange(10)
print(arr[0:8:2])

arr=  np.array([[1,2,3,4],[5,6,7,8], [9,10,11,12]])
print(arr[:2, :2])


[0 2 4 6]
[[1 2]
 [5 6]]


In [8]:
#integer indexing

arr= np.array([[1,2],[3,4],[5,6]])
print(arr[[0,1,2],[0,1,1]])

[1 4 6]


In [10]:
arr= np.arange(9)
reshape_arr =arr.reshape(3,3)
print(reshape_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
arr = np.arange(8).reshape(2,4)
print(arr.flat[4])

4


In [12]:
arr = np.arange(8).reshape(2,4)
print(arr.flatten())

[0 1 2 3 4 5 6 7]


In [13]:
arr = np.arange(8).reshape(2,4)
print(arr.transpose())

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [14]:
a= np.array([[1],[2],[3]])
b = np.array([4,5,6])
c = a + b
print(c)

bc= np.broadcast(a, b)
x = np.zeros(bc.shape)

x.flat= [a + b for (a,b) in bc]
print(x)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr_resized = np.resize(arr, (3,3))
print(arr_resized)