In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr[0], arr[1], arr[2])
arr[2] = 4
print(arr)

#rank 2 array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)
print(arr2[0,0], arr2[0,1], arr2[1,0])
print(arr2[-1])

<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]


In [3]:
#array of zeros
zero = np.zeros((2,2))
print(zero)

#array of ones
one = np.ones((1,2))
print(one)

#array of constant value
constant = np.full((2,2), 5)
print(constant)

#one on diagonal
diag = np.eye(3)
print(diag)

#change diag start index
diag = np.eye(4, k=1)
print(diag)

#array of random values
rand = np.random.random((2,2))
print(rand)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.43997433 0.33363257]
 [0.94876404 0.49935972]]


In [6]:
#array indexing
arr = np.arange(10)
print(arr[0:8:2])       #every 2 number from 0 up not including 8

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:2, :2])

[0 2 4 6]
[[1 2]
 [5 6]]


In [11]:
#integer indexing

arr = np.array([[1,2], [3,4], [5,6]])
print(arr[[0,1,2],[0,1,1]])             #[0,1,2] specifies rows (all rows) [0,1,1] specifies columns

[1 4 6]


In [12]:
arr = np.arange(9)
reshape_arr = arr.reshape(3,3)          #reshape array into 3x3 array
print(reshape_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
arr = np.arange(8).reshape(2,4)
print(arr.flat[4])              #flat turns array into 1d array, 4 is index

4


In [14]:
arr = np.arange(8).reshape(2,4)
print(arr.flatten())            #print array as 1d array

[0 1 2 3 4 5 6 7]


In [15]:
arr = np.arange(8).reshape(2,4)
print(arr.transpose())          #turns 2x4 array into 4x2 array

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [16]:
#numpy automatically supports broadcasting
a = np.array([[1], [2], [3]])
b = np.array([4,5,6])
c = a+b
print(c)

#behind the scenes
bc = np.broadcast(a, b)
x = np.zeros(bc.shape)
x.flat = [a+b for (a,b) in bc]
print(x)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [17]:
arr = np.array([[1,2,3], [4,5,6]])
arr_resized = np.resize(arr, (3,3))     #resizes array into 3x3, repeats elements for missing 3 values
print(arr_resized)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [18]:
unique = np.unique([1,1,2,2,3,3])
print(unique)                           #removes repeated values

arr = np.array([[1,1], [2,3]])
print(np.unique(arr))                   #call unique on separate array

arr = np.array(['a', 'b', 'b', 'c', 'a'])       #unique works on characters as well
unique, indices = np.unique(arr,return_index=True) #can set variable to index
print(unique, indices)

count = np.unique(arr, return_counts=True)      #tuple containing value, count
print(count[0], count[1])

[1 2 3]
[1 2 3]
['a' 'b' 'c'] [0 1 3]
['a' 'b' 'c'] [2 2 1]
