In [1]:
import numpy as np 

In [2]:
arr = np.array([1,2,3])
print(type(arr))

<class 'numpy.ndarray'>


In [3]:
print(arr.dtype)

int32


In [4]:
print(arr.shape)

(3,)


In [5]:
print(arr[0], arr[1], arr[2])

1 2 3


In [6]:
arr[2] = 4
print(arr)

[1 2 4]


In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.shape)
print(arr2[0,0], arr2[0,1], arr2[1,0])
print(arr2[-1])

(2, 3)
1 2 4
[4 5 6]


In [8]:
zero = np.zeros([2,2])
print(zero)

[[0. 0.]
 [0. 0.]]


In [9]:
one = np.ones((1,2))
print(one)

[[1. 1.]]


In [10]:
constant = np.full((2,2), 5)
print(one)

[[1. 1.]]


In [11]:
diag = np.eye(3)
print(diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
diag = np.eye(4, k=1)
print(diag)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [14]:
rand = np.random.random((2,2))
print(rand)

[[0.50855425 0.34879876]
 [0.86167599 0.21616382]]


In [15]:
arr = np.arange(10)
print(arr[0:8:2])

[0 2 4 6]


In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[:2, :2])

[[1 2]
 [5 6]]


In [18]:
arr = np.array([[1,2], [3,4], [5,6]])
print(arr[[0,1,2], [0,1,1]])

[1 4 6]


In [20]:
arr = np.arange(9)
reshape_arr = arr.reshape(3,3)
print(reshape_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
arr = np.arange(8).reshape(2,4)
print(arr.flat[4])

4


In [25]:
arr = np.arange(8).reshape(2,4)
print(arr.flatten())

[0 1 2 3 4 5 6 7]


In [26]:
arr = np.arange(8).reshape(2,4)
print(arr.transpose())

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
