In [1]:
import numpy as np

In [3]:
# create rank 1 dim array
arr = np.array([1, 2, 3])
print(type(arr))                     # output <class 'numpy.ndarray'>
print(arr.dtype)                     # outputs int64
print(arr.shape)                     # output (3,)
print(arr[0], arr[1], arr[2])        # output 1 2 3
arr[2] =4                            #change last element to 4
print                                # output [1 2 4]

# create rank 2 array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)                         # output (2, 3)
print(arr2[0, 0], arr2[0, 1], arr2[1, 0])  # outputs (2, 3)
print(arr2[-1])                             # outputs last element [4, 5, 6]

<class 'numpy.ndarray'>
int64
(3,)
1 2 3
(2, 3)
1 2 4
[4 5 6]


In [9]:
# create an array of zeros with 2 dim and size of 2 each
zero = np.zeros((2, 2))                             # outputs "[[0.  0."
                                                    #          [0. 0.]]"


# create an array of ones with 1 dim and size of each
one = np.ones((1, 2))
print(one)                                      # outputs "[[1.  1.]]"

#create a new array with given shape, type, and filled with value
constant = np.full((2,2), 5)      # default type is float
print(constant)                   #outputs "[[5 5]
                                  #          [5 5]]"

# create a 2 - D array with 1 on diagonal and 0 on others
diag = np.eye(3)                  # number of rows
print(diag)                       # outputs [[1. 0. 0.]
                                  #          [0. 1. 0.]
                                  #          [0. 0. 1.]]

# diag starts at index 1
diag = np.eye(4, k=1)
print(diag)                       # outputs [[1. 1. 0. 0.]
                                  #          [0. 0. 1. 0.]
                                  #          [0. 0. 0. 1.]
                                  #          [0. 0. 0. 0.]

# create an array with random values
rand = np.random.random((2,2))
print(rand)



[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.69616508 0.04451545]
 [0.91765357 0.44204349]]


In [8]:
# Array indexing
arr = np.arange(10)              # generate array [0 1 2 3 4 5 6 7 8 9]
print(arr[0:8:2])                 # every two number from 0 up to but not include 8

# create rank 2 with shape (3, 4) array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:2, :2])                # outputs [[1 2]
                                  #          [5 6]]

[0 2 4 6]
[[1 2]
 [5 6]]


In [ ]:
# integer indexing

arr = np.array([[1,2], [3, 4], [5, 6]])
print(arr[[0, 1, 2], [0, 1, 1]])             # outputs [1 4 6]

# arr[[0, 1, 2], [0, 1, 1]] is equivalent to [arr[0,0], arr[1, 1, arr[2, 1]]]

In [11]:
arr = np.arange(9)                           # create [0, 1, 2, 3, 4, 5, 6, 7, 8]
reshape_arr = arr.reshape(3, 3)               # reshape 1-D arr to 2-d with (3, 3)
print(reshape_arr)                           # output    [[0 1 2]
                                             #            [3 4 5]
                                             #            [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
arr = np.arange(8).reshape(2, 4)             # generates [[0, 1, 2, 3],
                                             #            [4, 5, 6, 7]]
# print(arr[4])                              # access arr[4] would cause an error
                                             # since index out of range 
                                             #
print(arr.flat[4])                           # turned arr into 1-D array ->[0, 1, 2, 3, 4, 5, 6, 7 ,8]

4


In [13]:
# flatten()

Collapse to 1-D array and return a copy of the array

arr = np.arange(8).reshape(2, 4)             # generates [[0, 1, 2, 3]
                                             #            [4, 5, 6, 7]]
print(arr.flatten())                         # outputs [0, 1, 2, 3, 4, 5, 6, 7, 8]

[0 1 2 3 4 5 6 7]


In [14]:
# transpose()
# Permutes the dimension of an array

arr = np.arange(8).reshape(2, 4)            # generates [[0, 1, 2, 3],
                                            #            [4, 5, 6, 7]]
print(arr.transpose())                      

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [15]:
# broadcast()

# numpy builtsupport broadcasting
a= np.array([[1], [2], [3]])
b= np.array([4, 5, 6])                    #[[1+4, 3+4], [1+5, so on], [1+6], so on]
c = a+b
print(c)

#this is what it was doing for us
bc = np.broadcast(a, b)                  # return broadcast object, and may be used as iterator
x = np.zeros(bc.shape)                   # x is [0 0 0]
                                         #      [0 0 0]
                                         #      [0 0 0]
x.flat = [a + b for (a,b) in bc]         # turn x into 1-D array for get all values after adding them
print(x)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [17]:
# resize()
#Returns a new array with the specified shape. If the new size is greater #than the original, the repeited copies of the entries in the original are #contained

arr = np.array([[1,2,3], [4,5,6]])        # shape is [2, 3]
arr_resized = np.resize(arr, (3,3))       # resize to (3,3)
print(arr_resized)                         # it's bigger, so it repeated the first raw to fill up

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [19]:
# unique()
# Finds the unique elements of an array

unique = np.unique([1, 1, 2, 2, 3, 3])
print(unique)                         

arr = np.array([[1, 1], [2, 3]])
print(np.unique(arr))

arr = np.array(['a', 'b', 'c', 'a'])
unique, indices = np.unique(arr, return_index=True)     # returns index of the first unique values
print(unique, indices)              
count = np.unique(arr, return_counts=True)             # return tuple object
print(count[0], count[1])               # first array is is unique value, secons is number of occurence

[1 2 3]
[1 2 3]
['a' 'b' 'c'] [0 1 2]
['a' 'b' 'c'] [2 1 1]
