In [2]:
import numpy as np

nwalks = 5000
nsteps = 1000
target = -50

# requirement 1: Use the random seed of 1234 to generate the same random sequences
np.random.seed(1234)
# requirement 2: Generate normally distributed steps with mean 0 and standard deviation of 0.25
steps = np.random.normal(loc = 0, scale = 0.25, size = (nwalks, nsteps))
# requirement 3: Set the step +1 if the generated random number is nonnegative; otherwise -1.
steps = np.where(steps > 0 , 1, -1)
###print('=========== steps')
###print(steps)

# requirement 4,5: Adding up to calculate the crossing times
randomWalks = np.cumsum(steps, 1)
###print('=========== walks')
###print(randomWalks)

# A
minRandomWalks = np.where(randomWalks == target, 1, 0).any(1)
print('The number of random walks that hit -50 :')
print(minRandomWalks.sum())

# B
minCrossingTimes = (np.where(randomWalks == target, 1, 0)).argmax(1)
print('The average minimum crossing time:')
print(minCrossingTimes.mean())

=========== steps
[[ 1 -1  1 ...  1  1 -1]
 [-1 -1  1 ...  1  1 -1]
 [-1  1 -1 ...  1  1  1]
 ...
 [ 1  1 -1 ...  1 -1  1]
 [ 1 -1  1 ...  1 -1  1]
 [ 1  1  1 ... -1  1 -1]]
=========== walks
[[  1   0   1 ...  14  15  14]
 [ -1  -2  -1 ...  24  25  24]
 [ -1   0  -1 ...  24  25  26]
 ...
 [  1   2   1 ...  -8  -9  -8]
 [  1   0   1 ... -20 -21 -20]
 [  1   2   3 ... -14 -13 -14]]
The number of random walks that hit -50 :
604
The average minimum crossing time:
82.1104
