In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.shape

(3,)

In [6]:
arr[0]

1

In [7]:
arr[2] = 4

In [8]:
arr

array([1, 2, 4])

In [9]:
arr.size

3

In [11]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
arr2.shape

(2, 3)

In [13]:
arr2[0,  0]

1

In [14]:
arr2[0, 1]

2

In [16]:
arr2[1][2]

6

In [18]:
arr2[-2]

array([1, 2, 3])

In [19]:
zero = np.zeros((2, 2))
print(zero)

[[0. 0.]
 [0. 0.]]


In [20]:
one = np.ones((1, 2))

In [21]:
print(one)

[[1. 1.]]


In [22]:
one = np.ones((1, 3))

In [23]:
one

array([[1., 1., 1.]])

In [26]:
one = np.zeros((1, 3))

In [27]:
one

array([[0., 0., 0.]])

In [28]:
print(one)

[[0. 0. 0.]]


In [29]:
constant = np.full((2, 2), 5)

In [30]:
constant

array([[5, 5],
       [5, 5]])

In [31]:
diag = np.eye(3)

In [32]:
print(diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
diag = np.eye(4, k = 0)

In [36]:
print(diag)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
rand = np.random.random((2, 2))

In [38]:
rand

array([[0.31215675, 0.85854041],
       [0.97735294, 0.39532133]])

In [39]:
rand = np.random.randint((2, 2))

In [40]:
rand

array([1, 1])

In [42]:
arr = np.arange(10)

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
print(arr[0:8:2])

[0 2 4 6]


In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [46]:
print(arr[:2, :2])

[[1 2]
 [5 6]]


In [47]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

In [48]:
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
print(arr[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [50]:
arr = np.arange(9)

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
rearr = arr.reshape(3, 3)

In [53]:
rearr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr = np.arange(8).reshape(2, 4)

In [55]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
arr.flat

In [57]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
arr.flat[4]

4

In [59]:
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [60]:
arr[4]

IndexError: index 4 is out of bounds for axis 0 with size 2

In [61]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
arr = np.arange(9).reshape(3, 3)

In [63]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [65]:
a = np.array([[1], [2], [3]])

In [66]:
b = np.array([4, 5, 6])

In [67]:
c = a + b

In [68]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [69]:
bc = np.broadcast(a, b)

In [70]:
bc

In [71]:
x = np.zeros(bc.shape)

In [72]:
x.flat = [a + b for (a, b) in bc]

In [73]:
print(x)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [75]:
arr_resized = np.resize(arr, (3, 3))

In [76]:
arr_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [78]:
unique = np.unique([1, 1, 1, 1, 1, 3, 4, 5, 6, 3, 4, 5, 5])

In [79]:
unique

array([1, 3, 4, 5, 6])

In [80]:
arr = np.array([[1, 1], [2, 3]])

In [81]:
print(arr)

[[1 1]
 [2 3]]


In [82]:
print(np.unique(arr))

[1 2 3]


In [83]:
arr = np.array(['a', 'b', 'b', 'c', 'a'])

In [84]:
unique, indices = np.unique(arr, return_index = True)

In [85]:
print(unique, indices)

['a' 'b' 'c'] [0 1 3]


In [86]:
count = np.unique(arr, return_counts= True)

In [87]:
print(count[0], count[1])

['a' 'b' 'c'] [2 2 1]
