In [76]:
import numpy as np

In [77]:
# create rank 1 dim array
arr = np.array([1, 2, 3])
print(type(arr))                            # outputs <class 'numpy.ndarray'>
print(arr.dtype)                            # outputs int64
print(arr.shape)                            # outputs (3, )
print(arr[0], arr[1], arr[2])               # outputs 1 2 3
arr[2] = 4                                  # change last element to 4
print(arr)                                  # outputs [1 2 4]

# create rank 2 array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)                           # outputs (2, 3)
print(arr2[0, 0], arr2[0, 1], arr2[1, 0])   # outputs 1 2 4
print(arr2[-1])                             # outputs last element

<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]


In [78]:
# create an array of zeros with 2 dim and size of 2 each
zero = np.zeros((2,2))
print(zero)                                 # outputs "[[0. 0.]
                                            #           [0. 0.]]"

# create an array of ones with 1 dim and size of 2 each
one = np.ones((1,2))
print(one)                                  # outputs "[[1. 1.]]"

# create a nee array with given shape, type, and filled value
constant = np.full((2,2), 5)                # default type is float
print(constant)                             # outputs "[[5 5]
                                            #           [5 5]]"

# create a 2-D array with 1 on diagonal and 0 on others
diag = np.eye(3)                            # number of rows
print(diag)                                 # outputs [[1. 0. 0.]
                                            #          [0. 1. 0.]
                                            #          [0. 0. 1.]]

#diag starts at index 1
diag = np.eye(4, k=1)               
print(diag)                                 # outputs [[0. 1. 0. 0.]
                                            #          [0. 0. 1. 0.]
                                            #          [0. 0. 0. 1.]
                                            #          [0. 0. 0. 0.]]

# create an array with random values
rand = np.random.random((2,2))
print(rand)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.71868231 0.72142989]
 [0.98611563 0.66626303]]


In [79]:
# integer indexing

arr = np.array([[1,2], [3, 4], [5, 6]])
print(arr[[0, 1, 2], [0, 1, 1]])                # outputs [1 4 6]

# arr [[0, 1, 2], [0, 1, 1]] is equivalent to [arr[0, 0], arr[1, 1, arr[2, 1]]]

[1 4 6]


In [80]:
arr = np.arange(9)                         # create [0, 1, 2, 3, 4, 5, 6, 7, 8]
reshape_arr = arr.reshape(3, 3)             # reshape 1-D arr to 2-D with (3, 3)
print(reshape_arr)                          # outputs  [[0 1 2]
                                            #           [3 4 5]
                                            #           [6 7 8]]



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [81]:
arr = np.arange(8).reshape(2, 4)           # generates [[0, 1, 2, 3],
                                            #            [4, 5, 6, 7]]

# print (arr[4])                            # access arr[4] would cause an error
                                            # since index out of range

print(arr.flat[4])                          # turned arr into 1-D array -> [0,1,2,3,4,5,6,7]
                                            # then indexing at 4
                                            # outputs 4

4


In [82]:
arr = np.arange(8).reshape(2, 4)           # generates [[0, 1, 2, 3],
                                            #            [4, 5, 6, 7]]
print(arr.flatten())                        # outputs [0,1,2,3,4,5,6,7,8]

[0 1 2 3 4 5 6 7]


In [83]:
arr = np.arange(8).reshape(2, 4)           # generates [[0, 1, 2, 3],
                                            #            [4, 5, 6, 7]]
print(arr.transpose())                      # outputs [[0 4]
                                            #          [1 5]
                                            #          [2 6]
                                            #          [3 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [84]:
# numpy built-in supports boardcasting
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
c = a + b                               # [[1+4, 2+4, 3+4], [1+5, so on], [1+6, so on]]
                                        # outputs [[5 6 7]
                                        #          [6 7 8]
                                        #          [7 8 9]]
# this is what it was doing for us
bc = np.broadcast(a, b)                 # return broadcast object, and may be used as an iterator
x = np.zeros(bc.shape)                  # x is [[0 0 0]
                                        #       [0 0 0]
                                        #       [0 0 0]]
x.flat = [a + b for (a,b) in bc]        # turn x into 1-D array for get all values after adding them
print(x)                                # now x is back to 3x3 with [[5., 6., 7.],
                                        #                           [6., 7., 8.],
                                        #                           [7., 8., 9.]]

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [85]:
arr = np.array([[1,2,3], [4,5,6]])          # shape is (2, 3)
arr_resized = np.resize(arr, (3,3))         # resize to (3, 3)
print(arr_resized)                          # it's bigger, so it repeated the first row to fill up
                                            # here it is [[1 2 3]
                                            #             [4 5 6]
                                            #             [1 2 3]]

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [86]:
unique = np.unique([1, 1, 2, 2, 3, 3])
print(unique)                               # outputs [1 2 3]

arr = np.array([[1, 1], [2, 3]])
print(np.unique(arr))                       # outputs [1 2 3]

arr = np.array(['a', 'b', 'c', 'a'])
unique, indices = np.unique(arr, return_index=True)     # returns index of the first unique values
print(unique, indices)                      # outputs ['a' 'b' 'c'] [0 1 3]

count = np.unique(arr, return_counts=True)  # return tuple object
print(count[0], count[1])

[1 2 3]
[1 2 3]
['a' 'b' 'c'] [0 1 2]
['a' 'b' 'c'] [2 1 1]
