In [7]:
import numpy as np
import pandas as pd

In [2]:
trans = pd.DataFrame({"A":[12,4,5,None,1],
                      "B":[7,2,54,3,None],
                      "C":[20,16,11,3,8],
                      "D":[14,3,None,2,6]},
                      index=['Row_1','Row_2','Row_3','Row_4','Row_5'])
trans

A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

In [3]:
result = trans.transform(lambda x : x + 10)
result

A     B   C     D
Row_1  22.0  17.0  30  24.0
Row_2  14.0  12.0  26  13.0
Row_3  15.0  64.0  21   NaN
Row_4   NaN  13.0  13  12.0
Row_5  11.0   NaN  18  16.0

In [8]:
result2 = trans.transform([np.sqrt, np.exp])
result2

A                        B                       C  \
           sqrt            exp      sqrt           exp      sqrt   
Row_1  3.464102  162754.791419  2.645751  1.096633e+03  4.472136   
Row_2  2.000000      54.598150  1.414214  7.389056e+00  4.000000   
Row_3  2.236068     148.413159  7.348469  2.830753e+23  3.316625   
Row_4       NaN            NaN  1.732051  2.008554e+01  1.732051   
Row_5  1.000000       2.718282       NaN           NaN  2.828427   

                            D                
                exp      sqrt           exp  
Row_1  4.851652e+08  3.741657  1.202604e+06  
Row_2  8.886111e+06  1.732051  2.008554e+01  
Row_3  5.987414e+04       NaN           NaN  
Row_4  2.008554e+01  1.414214  7.389056e+00  
Row_5  2.980958e+03  2.449490  4.034288e+02

In [9]:
#10 random numbers from 10-200
x = np.random.randint(10,200,size=10)
x

array([ 15, 135, 148, 178,  61, 132,  53,  53, 122, 179])

In [12]:
#In this step, we will discretize where 50 is the threshold to divide the data into two categories: one less than 50 and ones above than 50.
np.digitize(x,bins=[50])

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
#There are 3 categories here: 0, 1, and 2. 0 category is the values less than 50, 1 category is the value less than 100 and category 3 has the value more than 100.
np.digitize(x,bins=[50,100])

array([0, 2, 2, 2, 1, 2, 1, 1, 2, 2])

In [14]:
df = pd.DataFrame({"height": x})
df

height
0      15
1     135
2     148
3     178
4      61
5     132
6      53
7      53
8     122
9     179

In [15]:
#create new column 'binned' with interval
df['binned'] = pd.cut(x=df['height'],bins=[0,25,50,100,200])
df

height      binned
0      15     (0, 25]
1     135  (100, 200]
2     148  (100, 200]
3     178  (100, 200]
4      61   (50, 100]
5     132  (100, 200]
6      53   (50, 100]
7      53   (50, 100]
8     122  (100, 200]
9     179  (100, 200]

In [16]:
df['bin_label'] = pd.cut(x=df['height'],bins=[0,25,50,100,200],labels=[1,2,3,4])
df

height      binned bin_label
0      15     (0, 25]         1
1     135  (100, 200]         4
2     148  (100, 200]         4
3     178  (100, 200]         4
4      61   (50, 100]         3
5     132  (100, 200]         4
6      53   (50, 100]         3
7      53   (50, 100]         3
8     122  (100, 200]         4
9     179  (100, 200]         4

In [17]:
pd.qcut(df['height'],q=5)

0    (14.999, 53.0]
1    (133.2, 154.0]
2    (133.2, 154.0]
3    (154.0, 179.0]
4      (53.0, 97.6]
5     (97.6, 133.2]
6    (14.999, 53.0]
7    (14.999, 53.0]
8     (97.6, 133.2]
9    (154.0, 179.0]
Name: height, dtype: category
Categories (5, interval[float64]): [(14.999, 53.0] < (53.0, 97.6] < (97.6, 133.2] < (133.2, 154.0] < (154.0, 179.0]]

In [22]:
degrees = ["none","cum laude","magna cum laude","summa cum laude"]
student_results = [3.93,3.24,2.80,2.83,3.91,3.698,3.731,3.25,3.24,3.82,3.22]
student_results.sort(reverse=True)

student_results_degrees = pd.cut(student_results,[0,3.6,3.8,3.9,4.0],labels=degrees)
honor = pd.DataFrame({'grades': student_results,
                     'honors': student_results_degrees})
honor

NameError: name 'student_results_degrees' is not defined